### ISSUE TITLE
Inheritance of Sprite class

### ISSUE THREAD

**Issue by aechaves** [finnvoor/PlaydateKit#11]
Hi! First of all great work on this!

Question: Is inheritance between classes something that is supported (or to be supported in the future)?

Right now I'm trying to make a subclass of the Sprite class, but I get this nasty error when trying to compile with `swift package pdc`

```
[...]
building pdex.elf
/usr/local/playdate/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: /Users/angelo/Projects/Swift/playdate/unicode-survivors/.build/plugins/PDCPlugin/outputs/unicodesurvivors_device.o:(.data+0xc): undefined reference to `$s18playdatekit_device8PlaydateO6SpriteOADC7pointerAFs13OpaquePointerV_tcfC'
collect2: error: ld returned 1 exit status
error: ccFailed(exitCode: 1)
```
Note: I had to mark the Sprite class as `open` in order to be able to subclass it

**Comment by finnvoor** [comment]
Thanks for the report! This seems to me like another bug in the Swift compiler, not 100% sure.

Reproducible by creating one module that contains an open class with a non-public init, and another module containing a subclass.

Module 1:
```swift
open class Foo {
    init() {}
}
```

Module 2:
```swift
class Bar: Foo {}
```

I assume this is something that should work, so this should be supported eventually!

cc @rauhul

**Comment by rauhul** [comment]
Definitely a bug! the absolute best thing you can (short of fixing the bug yourself) is filing a GitHub issue on apple/swift with a minimal repro. Additionally please tag both me and @kubamracek in the issue!

The best repro would be two simple files with the content you have here and either a single command to repro the issue _or_ a script.

**Comment by finnvoor** [comment]
> Definitely a bug! the absolute best thing you can (short of fixing the bug yourself) is filing a GitHub issue on apple/swift with a minimal repro. Additionally please tag both me and @kubamracek in the issue!
> 
> The best repro would be two simple files with the content you have here and either a single command to repro the issue _or_ a script.

Good to know, I was starting to feel bad about tagging you in random bugs 😛

I'll try to get a minimal repro and open an issue.

**Comment by finnvoor** [comment]
https://github.com/apple/swift/issues/72531
