### ISSUE TITLE
XCode build (still) fails to produce .pdx, command line build works

### ISSUE THREAD

**Issue by cbackas42** [finnvoor/PlaydateKit#16]
I either can't re-open issues or can't figure out how, and I wasn't sure if there'd be a notice for a new comment in a closed issue so I'm opening a new one. Comment duplicated below:

Thanks for responding quickly! I tried your first suggestion, and tried building the unmodified PlaydateKit template project. The results were exactly the same, worked from the CLI but not from Xcode, the Simulator launched with no file loaded. Just like in my own project, this was the entire contents of TARGET_BUILD_DIR:
Mar 23 11:35 ./
Mar 23 11:35 ../
Mar 23 11:35 PackageFrameworks/
Mar 23 11:35 PlaydateKit.o
Mar 23 11:35 PlaydateKit.swiftmodule/
Mar 23 11:35 PlaydateKitTemplate.o
Mar 23 11:35 PlaydateKitTemplate.swiftmodule/

Then I pulled your latest changes. Same ultimate result, it still works from the CLI but not from Xcode; however, the Xcode behavior has changed as it now reports errors and doesn't launch the simulator. These are the console outputs from Command-R:
No matching processes belonging to you were found
Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
found Swift toolchain: org.swift.59202403191a
found Playdate SDK
[2K
[31m[1merror: [0mPlugin does not have access to a tool named ‘arm-none-eabi-gcc’
Program ended with exit code: 1

_Originally posted by @cbackas42 in https://github.com/finnvoor/PlaydateKit/issues/14#issuecomment-2016572529_

**Comment by finnvoor** [comment]
Hmm, that's weird that it can access the tool when run from the command line but not Xcode. Seems like maybe a permissions issue, I'll try to figure out what's going on.

**Comment by mgrider** [comment]
I have this same behavior, FWIW.

**Comment by finnvoor** [comment]
@cbackas42 @mgrider With 27d5a08 I just changed the plugin to specify the exact path to the Playdate SDK installed arm-none-eabi-gcc, which should fix the error you ran into and is a good change anyway to avoid conflicts with other installed tools. You might be able to build from Xcode now, or please let me know if you run into another error.

**Comment by cbackas42** [comment]
Thank you for continuing to try and resolve this... unfortunately, the 27d5a08 update didn't appear to change anything (yes, CLI still works)

New output looked like this:

`[2K
Updating https://github.com/finnvoor/PlaydateKit.git
[2K
Updated https://github.com/finnvoor/PlaydateKit.git (1.77s)
[2K
Working copy of https://github.com/finnvoor/PlaydateKit.git resolved at main (27d5a08)
Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
found Swift toolchain: org.swift.59202403191a
found Playdate SDK
building playdatekit_device.o
/Users/cbackas/Projects/PlaydateKitTemplate/.build/checkouts/PlaydateKit/Sources/PlaydateKit/Core/Display.swift:1:8: warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 1 │ public import CPlaydate
   │        ╰─ warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 2 │ 
 3 │ /// Functions pertaining to Playdate’s screen.

/Users/cbackas/Projects/PlaydateKitTemplate/.build/checkouts/PlaydateKit/Sources/PlaydateKit/Geometry/Rect.swift:1:8: warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 1 │ public import CPlaydate
   │        ╰─ warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 2 │ 
 3 │ // MARK: - Rect
building playdatekit_simulator.o
/Users/cbackas/Projects/PlaydateKitTemplate/.build/checkouts/PlaydateKit/Sources/PlaydateKit/Core/Display.swift:1:8: warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 1 │ public import CPlaydate
   │        ╰─ warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 2 │ 
 3 │ /// Functions pertaining to Playdate’s screen.

/Users/cbackas/Projects/PlaydateKitTemplate/.build/checkouts/PlaydateKit/Sources/PlaydateKit/Geometry/Rect.swift:1:8: warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 1 │ public import CPlaydate
   │        ╰─ warning: public import of 'CPlaydate' was not used in public declarations or inlinable code
 2 │ 
 3 │ // MARK: - Rect
building playdatekittemplate_device.o
building playdatekittemplate_simulator.o
copying resources
building pdex.elf
building pdex.dylib
running pdc
[2K
[31m[1merror: [0mPlugin does not have access to a tool named ‘pdc’
Program ended with exit code: 1`

Seems like something must be going wrong with the path contruction someplace, maybe it could print the paths it's working with when it can't find a tool?

**Comment by cbackas42** [comment]
Heh, somehow I looked at this several times before realizing that it DID change the result, we're complaining about 'pdc' instead of 'arm-none-eabi-gcc' and the build process got much further along. I must be tired or something!

**Comment by finnvoor** [comment]
Ah I didn't notice either, that's good.  I've done the same thing for `pdc` in 595717c, so hopefully it works now.

**Comment by cbackas42** [comment]
That did the trick! Thanks again!

**Comment by mgrider** [comment]
Very nice! Thanks for this!!!
