### ISSUE TITLE
docs directory causes build issues on Windows

### ISSUE THREAD

**Issue by alicerunsonfedora** [finnvoor/PlaydateKit#25]
It appears that PlaydateKit can't be cloned on a Windows machine because the documentation's information uses symbols that aren't allowed as file paths in Windows:

```
    error: unable to create file docs/data/documentation/playdatekit/graphics/drawbitmap(_:at:flip:).json: Invalid argument
    error: unable to create file docs/data/documentation/playdatekit/graphics/drawbitmap(_:at:xscale:yscale:).json: Invalid argument    
    error: unable to create file docs/data/documentation/playdatekit/graphics/drawellipse(in:linewidth:startangle:endangle:color:).json: Invalid argument
    error: unable to create file docs/data/documentation/playdatekit/graphics/drawline(_:linewidth:color:).json: Invalid argument       
    error: unable to create file docs/data/documentation/playdatekit/graphics/drawrect(_:color:).json: Invalid argument
    error: unable to create file docs/data/documentation/playdatekit/graphics/drawtext(_:at:).json: Invalid argument
```

Using `git config --global core.protectNTFS` seems to be ignored here as well. I recommend we convert the project's documentation website to use GitHub Actions to deploy the documentation live rather than hosting it in the docs dir.

**Comment by finnvoor** [comment]
I tried to get Github Actions working for the docs a few days ago but couldn't manage to get the `xcodebuild docbuild` command working using the latest version of Xcode and using the right build settings. Might give it another try, but another option is just to move the docs to a `gh-pages` branch.
