### ISSUE TITLE
How do I use/cast `OpaquePointer` to `Sprite`?

### ISSUE THREAD

**Issue by iain-reid** [finnvoor/PlaydateKit#50]
I'm pretty excited about this library - and the instructions worked perfectly! 

However I'm running into an issue (that may be my misunderstanding of how to use PlaydateKit!)

When I use `setUpdateFunction` on a sprite - the closure defaults to passing me a variable called `sprite` (which makes perfect sense - I probably want access to that sprite to do something with it) - but the type is `OpaquePointer`...

Is there a way to cast this into a PlaydateKit `Sprite`? What is the best way to use this?

**Comment by iain-reid** [comment]
Looks like a good solution. Thanks for the quick response - and great work!

**Comment by iain-reid** [comment]
Looks like a good solution. Thanks for the quick response - and great work!

**Comment by finnvoor** [comment]
done! example usage here:
https://github.com/finnvoor/PlaydateKitTemplate/blob/main/Sources/PlaydateKitTemplate/Game.swift
