### ISSUE TITLE
Cannot add package dependency

### ISSUE THREAD

**Issue by eugeniobaglieri** [finnvoor/PlaydateKit#54]
Hi, is the a way to add a package dependency to the template?
If I add an external package or an internal target as dependency, Xcode recognize the dependency without error, but during compile I get always the "module XXX not found" error.
Am I missing something?

**Comment by finnvoor** [comment]
At the moment the pdc plugin which is used to compile doesn't look for / support external packages. It shouldn't be too hard to recursively look for dependencies and at least support simple package dependencies, but at the moment I don't have too much time to dedicate to this. Happy to accept any PRs if someone else wants to work on it though.

A workaround is to copy all the source files from the dependency you want to add directly to the template.

**Comment by eugeniobaglieri** [comment]
HI @finnvoor , I developed something, here:

https://github.com/eugeniobaglieri/PlaydateKit/tree/support_multiple_packages

the code should be improved, but at least seems it works with local packages (and maybe with remote but have to test it, I did not have enough time to setup a package repository).
Let me know what do you think and feel free to propose changes

**Comment by finnvoor** [comment]
This looks like an excellent start. Ideally we would support C packages, recursively compile packages, and support multiple targets in a package, but I think what you have so far covers 95% of what most people want. A single swift dependency with some common utils is probably most common.

I'll look through this a bit more but definitely open a PR and we can get this merged soon.
