### ISSUE TITLE
`swift_deallocPartialClassInstance` error when early exit (throw) from `Bitmap`

### ISSUE THREAD

**Issue by finnvoor** [finnvoor/PlaydateKit#7]

**Comment by rauhul** [comment]
Root caused this to a bug in swiftc where early exits from a class init result in the usage of this symbol: https://swift.godbolt.org/z/33EqW6crh

tracked by: rdar://125193196 (swift_deallocPartialClassInstance: Cannot early return from class init by throwing) 

cc @kubamracek

**Comment by rauhul** [comment]
apple/swift#72502
