### ISSUE TITLE
No way of printing formatted string with floating numbers

### ISSUE THREAD

**Issue by YogurtTheHorse** [finnvoor/PlaydateKit#70]
Running

```swift
print("\(Display.refreshRate) FPS")
```

Will result in printing of `(cannot print value in embedded Swift) FPS`. It can be rounded to int but obviously it's not very handy if we want to print some smaller numbers or just need more precision and don't want to multiply it by 10^n. System->logToConsole could help but it's not fully implemented, unfortunately

Just a notice, I am new to swift so I can simply be mistaken. I can see a comment that logToConsole with formatting should be implemented but while it's not it seems there is no workaround to print numbers as default swift interpolation would say it's not allowed 

I tried to see how to implement binding itself but unfortunately my knowledge of swift and especially embedded version simply does not let me do this

**Comment by finnvoor** [comment]
Unfortunately there's not much that can be done about this at the moment, the Embedded Swift runtime does not currently support printing / converting floats to strings, and also doesn't support VarArgs so the Playdate format string functions can't be used either. A workaround given by @tyetrask in the Playdate Squad discord is to add your own helper function:

```swift
extension Float {
    public enum PrecisionDigits: Int {
        case one   = 10
        case two   = 100
        case three = 1000
        case four  = 10000
        case five  = 100000
        case six   = 1000000
        case seven = 10000000
        case eight = 100000000
        case nine  = 1000000000
    }
    
    public func toString(withPrecision: PrecisionDigits = .two) -> String {
        let integral = Int(self)
        let fractional = self - Float(integral)
        let fractionalPrecision = fractional * Float(withPrecision.rawValue)
        return "\(integral).\(Int(abs(fractionalPrecision)))"
    }
}
```

```swift
let value: Float = 1234.5678
let message = "this is a value: \(value.toString(withPrecision: .three))"
```

**Comment by YogurtTheHorse** [comment]
Yeah, this is something I came up with but we all know this is not very handy :D 

May be we can include some C wrapper for that specific function?

**Comment by finnvoor** [comment]
Added some stubs with wrappers around `formatString` so string interpolation + printing of Floats and Doubles now works 👌

**Comment by rauhul** [comment]
This can be made nicer with a `CustomStringInterpolation` and a protocol defining `toString` similar to `CustomStringConvertible`

**Comment by rauhul** [comment]
TBH this is something we need to improve on the language side

**Comment by finnvoor** [comment]
@rauhul is there a benefit to using `String.StringInterpolation` vs just implementing `CustomStringConvertible` for Float + Double? That works but also requires implementing a custom `print` function, whereas `CustomStringConvertible` works by default due to https://github.com/swiftlang/swift/blob/4ef187be9e7fb16ca92a5161bf4a867e7c32d509/stdlib/public/core/EmbeddedPrint.swift#L51-L64.

Definitely agree this would be nice to solve on the language side, I've heard a lot of people mention being unable to prevent Floats is limiting.
