### ISSUE TITLE
"Build and run directly in the simulator using Xcode" -> "Module 'Swift' cannot be imported in embedded Swift mode"

### ISSUE THREAD

**Issue by jverkoey** [finnvoor/PlaydateKit#93]
I have a fresh clone of the template repo at https://github.com/jverkoey/rolypolyadventure.

When I try to open the Package.swift and build in Xcode, I get the following error:

```
Module 'Swift' cannot be imported in embedded Swift mode
```

<img width="1052" alt="Screenshot 2024-09-23 at 2 37 23 PM" src="https://github.com/user-attachments/assets/0630f153-1a0b-4d45-a907-65428eedb318">

Sharing here as I've just ran into this, will update this issue as I find ways to work around / resolve this.

**Comment by jverkoey** [comment]
Seems related: https://devforum.play.date/t/swift-playdate-examples-build-error-on-m3-macbook-air/16822

**Comment by jverkoey** [comment]
`swift package pdc` from the command line works though.

**Comment by finnvoor** [comment]
Did you select the nightly toolchain in the Xcode > Toolchains menu item?

From the toolbar it looks like it's not set, which is usually what gives this error.

**Comment by jverkoey** [comment]
Oh! I haven't changed toolchains before and feel like I'm blind; where do I do that in Xcode?

**Comment by jverkoey** [comment]
<img width="568" alt="Screenshot 2024-09-23 at 3 04 39 PM" src="https://github.com/user-attachments/assets/05e875f8-47ae-41a9-9b37-e0082acdb6d9">

Ah found it in the Xcode menu. I was thrown off by the mention of the toolbar; where did you look in the screenshot to identify the selected toolchain?

**Comment by jverkoey** [comment]
<img width="646" alt="Screenshot 2024-09-23 at 3 05 49 PM" src="https://github.com/user-attachments/assets/cccefcb3-c7a4-4a66-b340-cab80cccaff9">

Ahh neat, there's a little link icon in the build bar.
